# Generated by Django 4.1.4 on 2023-01-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
