# Generated by Django 4.1.4 on 2023-01-10 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_poll_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 1, 10, 15, 8, 11, 217005)),
        ),
    ]
